// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Threading;
using System.Threading.Tasks;

namespace Microsoft.Extensions.AI;

/// <summary>Represents a real-time session.</summary>
/// <remarks>This interface provides methods to manage a real-time session and to interact with the real-time model.</remarks>
[Experimental("MEAI001")]
public interface IRealtimeSession : IDisposable
{
    /// <summary>Updates the session with new options.</summary>
    /// <param name="options">The new session options.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>A task that represents the asynchronous update operation.</returns>
    Task UpdateAsync(RealtimeSessionOptions options, CancellationToken cancellationToken = default);

    /// <summary>Gets a value indicating whether the session is currently connected.</summary>
    /// <returns><see langword="true"/> if the session is connected; otherwise, <see langword="false"/>.</returns>
    bool IsConnected { get; }

    /// <summary>Sends real-time messages and streams the response.</summary>
    /// <param name="updates">The sequence of real-time messages to send.</param>
    /// <param name="cancellationToken">A token to cancel the operation.</param>
    /// <returns>The response messages generated by the session.</returns>
    IAsyncEnumerable<RealtimeServerMessage> GetStreamingResponseAsync(
            IAsyncEnumerable<RealtimeClientMessage> updates, CancellationToken cancellationToken = default);
}
